### ISSUE TITLE
Mailchimp subscription not working?

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/blog#111]
I used the little box on the blog saying " Sign up for our blog and we'll send you information about Sphinx and Read the Docs on a regular basis. " a while back, but I didn't receive anything. I expected some sort of automated email on the new blog posts, for example. If it is not automated, I propose we discuss about what to do with it :)

**Comment by astrojuanlu** [comment]
@ericholscher Perhaps it's only me, but I think "subscribe to our blog" gives the impression that subscribers will receive new posts by email:

![Screenshot 2021-07-08 at 22-54-34 Recent posts — Read the Docs Blog](https://user-images.githubusercontent.com/316517/124989595-90b0cf00-e03f-11eb-9e4f-d5775e345bf4.png)

Definitely, if it was the intention, it is not happening :) (we published 2 or 3 posts since I opened this issue). And if it's not, what do you think about rephrasing it? We are not doing any email marketing now yet, though.

**Comment by ericholscher** [comment]
Looks like Mailchimp was disabled because we hit too many subscribers.

**Comment by ericholscher** [comment]
I've re-enabled it.

**Comment by astrojuanlu** [comment]
Thanks! Will close this issue when we observe evidence that it's working

**Comment by astrojuanlu** [comment]
Test email worked 👍🏽
