### ISSUE TITLE
Add call to action in `/jobs/` page

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/blog#136]
Since `/jobs/` is our most visited page, @MxRaCohen proposed some good ideas:

> There’s gotta be something we can put in /jobs/ like “thank you so much for wanting to support RtD. While we don’t have any open positions you can support us in other ways like keeping [ads] on your project page, addressing a [first issue], or directly” (by buying merch or sponsoring something idk)

**Comment by ericholscher** [comment]
We have an email us CTA, which is probably enough for now.

**Comment by MxRaCohen** [comment]
RIP Read The Socks™

Hope y’all’re doing well :)

**Comment by ericholscher** [comment]
@MxRaCohen haha, some day :)
