### ISSUE TITLE
Marketing for build.jobs

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/blog#160]
This is an announcement post for this feature. It can highlight some of the docs we've already written, and inline some of the neat examples we've figured out.

**Comment by ericholscher** [comment]
Initial push: https://twitter.com/readthedocs/status/1519363742869295105

**Comment by humitos** [comment]
@ericholscher besides the post written in #162 is there anything else required here? do you have something else in mind?

**Comment by humitos** [comment]
I did a quick research to know how people are using `build.jobs` and opened https://github.com/readthedocs/meta/discussions/23 to track that usage. From there, we can create more examples and get more ideas for promotion.

**Comment by ericholscher** [comment]
This is probably done-ish? We need some more concrete tasks here I think, instead of this placeholder.

**Comment by humitos** [comment]
The initial work is done, yes. We talked about keeping tweeting about this and finding more examples of _good usage_. I took another look at how people are using `build.jobs` but I didn't find anything super interesting to tweet about. Most of our users are either using the examples we have documented or some hacky custom solution they need for their use case that other users probably won't benefit from seeing them.

I updated the discussion with the latest example that I found, and I also took a look at `build.commands` --where I didn't find any real good usage we can comment about either.

So far we have:

- documentation page: https://docs.readthedocs.io/en/latest/build-customization.html
- blog post: https://blog.readthedocs.com/user-defined-build-jobs/
- announcing tweet: https://twitter.com/readthedocs/status/1527234995001040898
- tweet with an example: https://twitter.com/readthedocs/status/1527234995001040898

**Comment by humitos** [comment]
I updated the meta discussion with the new findings. Nothing too interesting to promote 😄 . I think we can call this work done for now and keep updating that meta discussion with more relevant use cases. Besides promoting them when finding something interesting, that data will help us to understand more our users and their use cases in the future, and make better decisions about how the new build system / contract / metadata / etc will work.

**Comment by ericholscher** [comment]
Yea, I think we can definitely be doing more to market it, but we need specific tasks.
