### ISSUE TITLE
Write a blog post using Metabase metrics

### ISSUE THREAD

**Issue by humitos** [readthedocs/blog#174]
I didn't thought too much about the content yet, but I'd love to see some of the nice graphs we are getting from Metabase in a blog post commenting how people is using our platform. It could be related with the science work that @benjaoming is doing too or something more generic, or both!

**Comment by humitos** [comment]
I'm un-assigning this from myself because I've already have #175 where we will be talking about something more generic using the Metabase data. I mentioned "the science work that @benjaoming is doing" because I noticed him excited about these graphs while I was sharing them in Slack. If he doesn't feel like writing a blog post about this currently we can re-schedule this work or close it for now.

**Comment by ericholscher** [comment]
I think we just shipped this right?
