### ISSUE TITLE
Write blog post about `build.commands`

### ISSUE THREAD

**Issue by humitos** [readthedocs/blog#178]
We have done good work on the documentation page about `build.jobs` and `build.commands`, https://docs.readthedocs.io/en/latest/build-customization.html. However, we haven't write a blog post announcing `build.commands` in beta state.

I think it's a good timing for this since we have been testing it during some months and it's a good feature as it is, even with the current limitation that it has.

We wrote a blog post about `build.jobs` that we can use as a reference: https://blog.readthedocs.com/user-defined-build-jobs/

**Comment by ericholscher** [comment]
Strong agree on this!
